service: etherless

provider:
  name: aws
  runtime: nodejs12.x
  profile: etherless-server
  region: eu-central-1
  deploymentPrefix: etherless

functions:
  deploy:
    handler: lambdas/deployer/index.deploy
    environment:
      HOME: /tmp